[project]
name = "BrushstrokeNet"
version = "0.1.0"
description = "hello there"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
